# galaxy roles variables file

# galaxy/java
oracle_jdk_java_versions: [6, 7, 8, 9]
oracle_jdk_java_version_default: 8

# galaxy/nodejs
node_packages:
  - n
  - npm
  - bower
  - gulp
  - angular-cli
  - yo

# galaxy/oh-my-zsh
users:
  - username: "{{ username }}"