- name: Copy Java 6 binary file
  copy:
    src: ../files/{{ java_6_install_file }}
    dest: /usr/lib/jvm/
    owner: root
    group: root
    mode: 0775

- name: Install Java 6
  shell: cd /usr/lib/jvm/ && ./{{ java_6_install_file }}

- name: Rename Java 6 folder
  shell: mv /usr/lib/jvm/{{ java_6_installed_folder }} /usr/lib/jvm/java-6-oracle

- name: Changing owner Java 6 folder
  file:
    path: /usr/lib/jvm/java-6-oracle
    owner: root
    group: root

- name: Update alternatives Java
  alternatives:
    name: java
    path: /usr/lib/jvm/java-6-oracle/bin/java
    link: /usr/bin/java

- name: Update alternatives Javac
  alternatives:
    name: javac
    path: /usr/lib/jvm/java-6-oracle/bin/javac
    link: /usr/bin/javac

- name: Update alternatives Jcontrol
  alternatives:
    name: jcontrol
    path: /usr/lib/jvm/java-6-oracle/bin/jcontrol
    link: /usr/bin/jcontrol

- name: Removing Java 6 installer file
  file: 
    path: /usr/lib/jvm/{{ java_6_install_file }}
    state: absent